// <auto-generated />
using System;
using DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SuggestionContext))]
    [Migration("20240218022441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "enhancement",
                            Description = "Easier to search for solutions based on a specific stack.",
                            Status = "live",
                            Title = "Add tags for solutions okay",
                            Upvotes = 144
                        },
                        new
                        {
                            Id = 2,
                            Category = "feature",
                            Description = "It would help people with light sensitivities and who prefer dark mode.",
                            Status = "planned",
                            Title = "Add a dark theme option",
                            Upvotes = 122
                        });
                });

            modelBuilder.Entity("Domain.Entities.SuggestionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("SuggestionsComment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Awesome idea! Trying to find framework-specific projects within the hubs can be tedious",
                            SuggestionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Please use fun, color-coded labels to easily identify them at a glance",
                            SuggestionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Also, please allow styles to be applied based on system preferences. I would love to be able to browse Frontend Mentor in the evening after my device’s dark mode turns on without the bright background it currently has.",
                            SuggestionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Content = "Second this! I do a lot of late night coding and reading. Adding a dark theme can be great for preventing eye strain and the headaches that result. It’s also quite a trend with modern apps and  apparently saves battery life.",
                            SuggestionId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.SuggestionCommentReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReplyingTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SuggestionCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("SuggestionsCommentReply");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "While waiting for dark mode, there are browser extensions that will also do the job. Search for 'dark theme' followed by your browser. There might be a need to turn off the extension for sites with naturally black backgrounds though.",
                            ReplyingTo = "hummingbird1",
                            SuggestionCommentId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            Content = "Good point! Using any kind of style extension is great and can be highly customizable, like the ability to change contrast and brightness. I'd prefer not to use one of such extensions, however, for security and privacy reasons.",
                            ReplyingTo = "annev1990",
                            SuggestionCommentId = 4,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "./assets/user-images/image-suzanne.jpg",
                            Name = "Suzanne Chang",
                            Username = "upbeat1811"
                        },
                        new
                        {
                            Id = 2,
                            Image = "./assets/user-images/image-thomas.jpg",
                            Name = "Thomas Hood",
                            Username = "brawnybrave"
                        },
                        new
                        {
                            Id = 3,
                            Image = "./assets/user-images/image-zena.jpg",
                            Name = "Zena Kelley",
                            Username = "velvetround"
                        },
                        new
                        {
                            Id = 4,
                            Image = "./assets/user-images/image-elijah.jpg",
                            Name = "Elijah Moss",
                            Username = "hexagon.bestagon"
                        },
                        new
                        {
                            Id = 5,
                            Image = "./assets/user-images/image-james.jpg",
                            Name = "James Skinner",
                            Username = "hummingbird1"
                        },
                        new
                        {
                            Id = 6,
                            Image = "./assets/user-images/image-anne.jpg",
                            Name = "Anne Valentine",
                            Username = "annev1990"
                        },
                        new
                        {
                            Id = 7,
                            Image = "./assets/user-images/image-ryan.jpg",
                            Name = "Ryan Welles",
                            Username = "voyager.344"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SuggestionComment", b =>
                {
                    b.HasOne("Domain.Entities.Suggestion", null)
                        .WithMany("Comments")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SuggestionCommentReply", b =>
                {
                    b.HasOne("Domain.Entities.SuggestionComment", null)
                        .WithMany("Replies")
                        .HasForeignKey("SuggestionCommentId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Suggestion", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entities.SuggestionComment", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
