certificate:
    namespace: default
    dnsNames:
      - domain: alexbartleynees.com
    secretName: website-tls
    issuerRef: 
      name: selfsigned-issuer
      kind: ClusterIssuer

issuers:
  type: selfsigned  # or letsencrypt
  selfsigned:
    enabled: true
  letsencrypt:
    enabled: false
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alexbartleynees@gmail.com
    ingressClass: nginx
        
