apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: product-feedback-cert
  namespace: default # or your namespace
spec:
  dnsNames:
    - product-feedback-api.io # your domain
  secretName: product-feedback-tls # this secret will be created
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
