apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-feedback-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: product-feedback-app.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: svc-product-feedback-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
