apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-feedback-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - product-feedback-app.io
      secretName: product-feedback-tls
  rules:
    - host: product-feedback-app.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
