apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-feedback-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: product-feedback-app.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-product-feedback-api
                port:
                  number: 8080
