apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-cert
  namespace: default # or your namespace
spec:
  dnsNames:
    - alex-bartleynees.me # your domain
  secretName: website-tls # this secret will be created
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
