apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
    - {{ .domain }}
  {{- end}}
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
