{{- if eq .Values.issuers.type "selfsigned" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}

{{- if eq .Values.issuers.type "letsencrypt" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuers.letsencrypt.name }}
spec:
  acme:
    server: {{ .Values.issuers.letsencrypt.server }}
    email: {{ .Values.issuers.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.issuers.letsencrypt.ingressClass | default "nginx" }}
{{- end}}
