ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex:
      "true"
      # Cache Configuration
    nginx.ingress.kubernetes.io/proxy-cache: "true"
    nginx.ingress.kubernetes.io/proxy-cache-path: "/var/cache/nginx keys_zone=STATIC:10m inactive=7d use_temp_path=off"
    # HTTP/2
    nginx.ingress.kubernetes.io/use-http2: "true"
    nginx.ingress.kubernetes.io/add-headers: |
      Vary: Accept-Encoding
    nginx.org/server-snippets: |
      brotli on;
      brotli_comp_level 6;
      brotli_min_length 1000;
      brotli_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        image/svg+xml;

      gzip on;
      gzip_comp_level 6;
      gzip_min_length 1000;
      gzip_proxied any;
      gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        image/svg+xml;
      charset_types 
        text/html 
        text/xml 
        text/plain 
        application/javascript 
        application/rss+xml 
        application/json;
      gzip_vary on;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
  maxBodySize: "8m"
  timeout:
    connect: "5"
    read: "60"
    send: "60"

  domain: alexbartleynees.com

  namespace: default

  services:
    - name: portfolio-site
      path: /images(/|$)(.*)
      pathType: Prefix
      serviceName: portfolio-site-svc
      servicePort: 4321
      annotations:
        nginx.ingress.kubernetes.io/proxy-cache-valid: "365d"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header Cache-Control "public, max-age=31536000";
    - name: portfolio-site
      path: /
      pathType: Prefix
      serviceName: portfolio-site-svc
      servicePort: 4321

tls:
  enabled: true
  secretName: website-tls
