ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
  
  domain: alexbartleynees.com

  namespace: default
  
  services:
    - name: product-feedback
      path: /product-feedback-app
      pathType: Prefix
      serviceName: nginx-service
      servicePort: 80

tls:
  enabled: true
  secretName: website-tls
