apiVersion: v1
kind: Service
metadata:
  name: {{ template "productfeedback.fullname" . }}-svc  
  labels:                          
    app: {{ template "productfeedback.name" . }}    
    chart: {{ template "productfeedback.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 5185
      targetPort: 5185   
      name: http       
      protocol: TCP 
  selector:
    app: {{ template "productfeedback.name" . }}    
    chart: {{ template "productfeedback.chart" . }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "productfeedback.fullname" . }}
  labels:
    app: {{ template "productfeedback.name" . }}
    chart: {{ template "productfeedback.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "productfeedback.name" . }}    
  template:
    metadata:
      labels:
        app: {{ template "productfeedback.name" . }}    
        chart: {{ template "productfeedback.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ConnectionStrings__SuggestionDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: sqlconnectionstring
                  key: SQL_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: product-feedback-api-config
          ports:
            - containerPort: 5185
              name: http  
              protocol: TCP 
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
