apiVersion: v1
kind: Service
metadata:
  name: {{ template "productfeedback.fullname" . }}-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 5185
  selector:
    app: {{ template "productfeedback.name" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "productfeedback.fullname" . }}
  labels:
    app: {{ template "productfeedback.name" . }}
    chart: {{ template "productfeedback.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "productfeedback.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "productfeedback.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: creativefree/product-feedback-api
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ConnectionStrings__SuggestionDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: sqlconnectionstring
                  key: SQL_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: product-feedback-api-config
          ports:
            - containerPort: 5185
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
